export const DEFAULT_PAGE_SIZE = 20
export const MAX_PAGE_SIZE = 100

export const TABBAR_HEIGHT_RPX = 116
export const TABBAR_ICON_SURFACE_WIDTH_RPX = 76
export const TABBAR_ICON_SURFACE_HEIGHT_RPX = 52
export const TABBAR_ICON_SIZE_RPX = 42
export const TABBAR_LABEL_SIZE_RPX = 20
export const TABBAR_INDICATOR_WIDTH_RPX = 16
export const TABBAR_INDICATOR_HEIGHT_RPX = 6

export const MOTION_DURATION_PRESS_MS = 120
export const MOTION_DURATION_STANDARD_MS = 180
export const MOTION_DURATION_ENTER_MS = 320
export const MOTION_DURATION_STAGGER_MS = 60
export const MOTION_EASING_STANDARD = 'cubic-bezier(0.22, 1, 0.36, 1)'

export const TOAST_DURATION_MS = 2000
